from datetime import timedelta
from unittest.mock import patch

from django.contrib.auth.models import User
from django.test import Client, TestCase
from django.utils import timezone

from monitors.access import get_monitor_or_404, visible_monitors
from monitors.models import Monitor

from .models import Team, TeamInvite, TeamMembership
from .utils import get_active_team, is_team_admin


class TeamModelTests(TestCase):
    def setUp(self):
        self.alice = User.objects.create_user("alice", "alice@test.com", "pass1234")
        self.bob = User.objects.create_user("bob", "bob@test.com", "pass1234")
        self.team = Team.objects.create(name="Platform", created_by=self.alice)
        TeamMembership.objects.create(
            team=self.team, user=self.alice, role=TeamMembership.Role.ADMIN
        )

    def test_str(self):
        self.assertEqual(str(self.team), "Platform")

    def test_membership_role_default_is_member(self):
        m = TeamMembership.objects.create(team=self.team, user=self.bob)
        self.assertEqual(m.role, TeamMembership.Role.MEMBER)

    def test_membership_unique_per_user(self):
        from django.db import IntegrityError

        with self.assertRaises(IntegrityError):
            TeamMembership.objects.create(team=self.team, user=self.alice)

    def test_admin_count(self):
        self.assertEqual(self.team.admin_count(), 1)

    def test_members_m2m(self):
        TeamMembership.objects.create(team=self.team, user=self.bob)
        self.assertEqual(set(self.team.members.all()), {self.alice, self.bob})


class TeamInviteModelTests(TestCase):
    def setUp(self):
        self.alice = User.objects.create_user("alice", "alice@test.com", "pass1234")
        self.team = Team.objects.create(name="Platform", created_by=self.alice)

    def test_token_autogenerated_and_unique(self):
        i1 = TeamInvite.objects.create(team=self.team, email="a@test.com")
        i2 = TeamInvite.objects.create(team=self.team, email="b@test.com")
        self.assertTrue(i1.token)
        self.assertNotEqual(i1.token, i2.token)

    def test_default_expiry_in_future(self):
        invite = TeamInvite.objects.create(team=self.team, email="a@test.com")
        self.assertGreater(invite.expires_at, timezone.now())

    def test_is_valid_true_for_fresh(self):
        invite = TeamInvite.objects.create(team=self.team, email="a@test.com")
        self.assertTrue(invite.is_valid)

    def test_is_valid_false_when_expired(self):
        invite = TeamInvite.objects.create(
            team=self.team,
            email="a@test.com",
            expires_at=timezone.now() - timedelta(days=1),
        )
        self.assertFalse(invite.is_valid)

    def test_is_valid_false_when_accepted(self):
        invite = TeamInvite.objects.create(
            team=self.team, email="a@test.com", accepted_at=timezone.now()
        )
        self.assertFalse(invite.is_valid)


class AccessHelperTests(TestCase):
    def setUp(self):
        self.alice = User.objects.create_user("alice", "alice@test.com", "pass1234")
        self.bob = User.objects.create_user("bob", "bob@test.com", "pass1234")
        self.carol = User.objects.create_user("carol", "carol@test.com", "pass1234")
        self.team = Team.objects.create(name="Platform", created_by=self.alice)
        TeamMembership.objects.create(
            team=self.team, user=self.alice, role=TeamMembership.Role.ADMIN
        )
        TeamMembership.objects.create(team=self.team, user=self.bob)

        self.personal = Monitor.objects.create(owner=self.alice, url="https://personal.com")
        self.shared = Monitor.objects.create(
            owner=self.alice, team=self.team, url="https://shared.com"
        )
        self.carol_mon = Monitor.objects.create(owner=self.carol, url="https://carol.com")

    def test_owner_sees_personal_and_team(self):
        self.assertEqual(
            set(visible_monitors(self.alice)), {self.personal, self.shared}
        )

    def test_member_sees_team_monitor(self):
        self.assertEqual(set(visible_monitors(self.bob)), {self.shared})

    def test_non_member_excluded(self):
        self.assertEqual(set(visible_monitors(self.carol)), {self.carol_mon})
        self.assertNotIn(self.shared, visible_monitors(self.carol))

    def test_get_monitor_or_404_for_member(self):
        self.assertEqual(
            get_monitor_or_404(self.bob, self.shared.pk), self.shared
        )

    def test_get_monitor_or_404_raises_for_non_member(self):
        from django.http import Http404

        with self.assertRaises(Http404):
            get_monitor_or_404(self.carol, self.shared.pk)

    def test_visible_monitors_no_duplicates(self):
        # Owner who is also a team member should not see the monitor twice.
        self.assertEqual(visible_monitors(self.alice).filter(pk=self.shared.pk).count(), 1)


class TeamCreateViewTests(TestCase):
    def setUp(self):
        self.client = Client()
        self.alice = User.objects.create_user("alice", "alice@test.com", "pass1234")
        self.client.login(username="alice", password="pass1234")

    def test_login_required(self):
        c = Client()
        response = c.post("/settings/teams/create/", {"name": "X"})
        self.assertEqual(response.status_code, 302)
        self.assertIn("/accounts/login/", response.url)

    def test_create_makes_creator_admin(self):
        response = self.client.post("/settings/teams/create/", {"name": "Platform"})
        team = Team.objects.get(name="Platform")
        self.assertRedirects(response, f"/settings/teams/{team.pk}/")
        self.assertTrue(is_team_admin(self.alice, team))

    def test_create_sets_active_team(self):
        self.client.post("/settings/teams/create/", {"name": "Platform"})
        team = Team.objects.get(name="Platform")
        self.assertEqual(self.client.session["active_team_id"], team.pk)


class TeamDetailPermissionTests(TestCase):
    def setUp(self):
        self.client = Client()
        self.alice = User.objects.create_user("alice", "alice@test.com", "pass1234")
        self.bob = User.objects.create_user("bob", "bob@test.com", "pass1234")
        self.carol = User.objects.create_user("carol", "carol@test.com", "pass1234")
        self.team = Team.objects.create(name="Platform", created_by=self.alice)
        TeamMembership.objects.create(
            team=self.team, user=self.alice, role=TeamMembership.Role.ADMIN
        )
        TeamMembership.objects.create(team=self.team, user=self.bob)

    def test_member_can_view_detail(self):
        self.client.login(username="bob", password="pass1234")
        response = self.client.get(f"/settings/teams/{self.team.pk}/")
        self.assertEqual(response.status_code, 200)

    def test_non_member_gets_404(self):
        self.client.login(username="carol", password="pass1234")
        response = self.client.get(f"/settings/teams/{self.team.pk}/")
        self.assertEqual(response.status_code, 404)

    def test_member_cannot_rename(self):
        self.client.login(username="bob", password="pass1234")
        response = self.client.post(
            f"/settings/teams/{self.team.pk}/rename/", {"name": "Hacked"}
        )
        self.assertEqual(response.status_code, 403)
        self.team.refresh_from_db()
        self.assertEqual(self.team.name, "Platform")

    def test_member_cannot_delete(self):
        self.client.login(username="bob", password="pass1234")
        response = self.client.post(f"/settings/teams/{self.team.pk}/delete/")
        self.assertEqual(response.status_code, 403)
        self.assertTrue(Team.objects.filter(pk=self.team.pk).exists())

    def test_member_cannot_invite(self):
        self.client.login(username="bob", password="pass1234")
        response = self.client.post(
            f"/settings/teams/{self.team.pk}/invite/",
            {"email": "x@test.com", "role": "member"},
        )
        self.assertEqual(response.status_code, 403)

    def test_admin_can_rename(self):
        self.client.login(username="alice", password="pass1234")
        self.client.post(f"/settings/teams/{self.team.pk}/rename/", {"name": "Renamed"})
        self.team.refresh_from_db()
        self.assertEqual(self.team.name, "Renamed")

    def test_delete_reverts_monitors_to_personal(self):
        monitor = Monitor.objects.create(
            owner=self.alice, team=self.team, url="https://shared.com"
        )
        self.client.login(username="alice", password="pass1234")
        self.client.post(f"/settings/teams/{self.team.pk}/delete/")
        monitor.refresh_from_db()
        self.assertIsNone(monitor.team_id)
        self.assertFalse(Team.objects.filter(pk=self.team.pk).exists())


class LastAdminGuardTests(TestCase):
    def setUp(self):
        self.client = Client()
        self.alice = User.objects.create_user("alice", "alice@test.com", "pass1234")
        self.bob = User.objects.create_user("bob", "bob@test.com", "pass1234")
        self.team = Team.objects.create(name="Platform", created_by=self.alice)
        self.alice_m = TeamMembership.objects.create(
            team=self.team, user=self.alice, role=TeamMembership.Role.ADMIN
        )
        self.bob_m = TeamMembership.objects.create(team=self.team, user=self.bob)
        self.client.login(username="alice", password="pass1234")

    def test_cannot_remove_last_admin(self):
        response = self.client.post(
            f"/settings/teams/{self.team.pk}/members/{self.alice.pk}/remove/"
        )
        self.assertRedirects(response, f"/settings/teams/{self.team.pk}/")
        self.assertTrue(
            TeamMembership.objects.filter(pk=self.alice_m.pk).exists()
        )

    def test_cannot_demote_last_admin(self):
        self.client.post(
            f"/settings/teams/{self.team.pk}/members/{self.alice.pk}/role/",
            {"role": "member"},
        )
        self.alice_m.refresh_from_db()
        self.assertEqual(self.alice_m.role, TeamMembership.Role.ADMIN)

    def test_can_remove_member(self):
        self.client.post(
            f"/settings/teams/{self.team.pk}/members/{self.bob.pk}/remove/"
        )
        self.assertFalse(TeamMembership.objects.filter(pk=self.bob_m.pk).exists())

    def test_can_demote_after_promoting_another(self):
        # Promote bob, then alice can be demoted.
        self.client.post(
            f"/settings/teams/{self.team.pk}/members/{self.bob.pk}/role/",
            {"role": "admin"},
        )
        self.client.post(
            f"/settings/teams/{self.team.pk}/members/{self.alice.pk}/role/",
            {"role": "member"},
        )
        self.alice_m.refresh_from_db()
        self.assertEqual(self.alice_m.role, TeamMembership.Role.MEMBER)


class TeamLeaveTests(TestCase):
    def setUp(self):
        self.client = Client()
        self.alice = User.objects.create_user("alice", "alice@test.com", "pass1234")
        self.bob = User.objects.create_user("bob", "bob@test.com", "pass1234")
        self.team = Team.objects.create(name="Platform", created_by=self.alice)
        TeamMembership.objects.create(
            team=self.team, user=self.alice, role=TeamMembership.Role.ADMIN
        )

    def test_sole_member_leave_deletes_team(self):
        self.client.login(username="alice", password="pass1234")
        response = self.client.post(f"/settings/teams/{self.team.pk}/leave/")
        self.assertRedirects(response, "/settings/teams/")
        self.assertFalse(Team.objects.filter(pk=self.team.pk).exists())

    def test_last_admin_with_members_cannot_leave(self):
        TeamMembership.objects.create(team=self.team, user=self.bob)
        self.client.login(username="alice", password="pass1234")
        self.client.post(f"/settings/teams/{self.team.pk}/leave/")
        self.assertTrue(
            TeamMembership.objects.filter(team=self.team, user=self.alice).exists()
        )

    def test_member_can_leave(self):
        TeamMembership.objects.create(team=self.team, user=self.bob)
        self.client.login(username="bob", password="pass1234")
        self.client.post(f"/settings/teams/{self.team.pk}/leave/")
        self.assertFalse(
            TeamMembership.objects.filter(team=self.team, user=self.bob).exists()
        )


class SwitchTeamTests(TestCase):
    def setUp(self):
        self.client = Client()
        self.alice = User.objects.create_user("alice", "alice@test.com", "pass1234")
        self.team = Team.objects.create(name="Platform", created_by=self.alice)
        TeamMembership.objects.create(
            team=self.team, user=self.alice, role=TeamMembership.Role.ADMIN
        )
        self.client.login(username="alice", password="pass1234")

    def test_switch_sets_session(self):
        self.client.post("/settings/teams/switch/", {"team_id": self.team.pk})
        self.assertEqual(self.client.session["active_team_id"], self.team.pk)

    def test_switch_to_personal_clears_session(self):
        self.client.post("/settings/teams/switch/", {"team_id": self.team.pk})
        self.client.post("/settings/teams/switch/", {"team_id": ""})
        self.assertNotIn("active_team_id", self.client.session)

    def test_cannot_switch_to_non_member_team(self):
        other = Team.objects.create(name="Other")
        response = self.client.post("/settings/teams/switch/", {"team_id": other.pk})
        self.assertEqual(response.status_code, 404)


class InviteFlowTests(TestCase):
    def setUp(self):
        self.client = Client()
        self.alice = User.objects.create_user("alice", "alice@test.com", "pass1234")
        self.bob = User.objects.create_user("bob", "bob@test.com", "pass1234")
        self.team = Team.objects.create(name="Platform", created_by=self.alice)
        TeamMembership.objects.create(
            team=self.team, user=self.alice, role=TeamMembership.Role.ADMIN
        )

    @patch("teams.views.resend.Emails.send")
    def test_admin_invite_creates_invite_and_sends_email(self, mock_send):
        with self.settings(RESEND_API_KEY="test-key"):
            self.client.login(username="alice", password="pass1234")
            self.client.post(
                f"/settings/teams/{self.team.pk}/invite/",
                {"email": "bob@test.com", "role": "member"},
            )
        invite = TeamInvite.objects.get(email="bob@test.com")
        self.assertEqual(invite.team, self.team)
        mock_send.assert_called_once()
        payload = mock_send.call_args.args[0]
        self.assertEqual(payload["to"], ["bob@test.com"])
        self.assertIn(invite.token, payload["text"])

    @patch("teams.views.resend.Emails.send")
    def test_invite_skipped_when_no_api_key(self, mock_send):
        with self.settings(RESEND_API_KEY=""):
            self.client.login(username="alice", password="pass1234")
            self.client.post(
                f"/settings/teams/{self.team.pk}/invite/",
                {"email": "bob@test.com", "role": "member"},
            )
        # Invite row still created, but no email attempted.
        self.assertTrue(TeamInvite.objects.filter(email="bob@test.com").exists())
        mock_send.assert_not_called()

    def test_accept_valid_invite_adds_membership(self):
        invite = TeamInvite.objects.create(
            team=self.team, email="bob@test.com", role=TeamMembership.Role.MEMBER
        )
        self.client.login(username="bob", password="pass1234")
        response = self.client.get(f"/teams/invite/{invite.token}/")
        self.assertRedirects(response, f"/settings/teams/{self.team.pk}/")
        self.assertTrue(
            TeamMembership.objects.filter(team=self.team, user=self.bob).exists()
        )
        invite.refresh_from_db()
        self.assertIsNotNone(invite.accepted_at)

    def test_accept_expired_invite_rejected(self):
        invite = TeamInvite.objects.create(
            team=self.team,
            email="bob@test.com",
            expires_at=timezone.now() - timedelta(days=1),
        )
        self.client.login(username="bob", password="pass1234")
        response = self.client.get(f"/teams/invite/{invite.token}/")
        self.assertRedirects(response, "/settings/teams/")
        self.assertFalse(
            TeamMembership.objects.filter(team=self.team, user=self.bob).exists()
        )

    def test_accept_used_invite_rejected(self):
        invite = TeamInvite.objects.create(
            team=self.team, email="bob@test.com", accepted_at=timezone.now()
        )
        self.client.login(username="bob", password="pass1234")
        self.client.get(f"/teams/invite/{invite.token}/")
        self.assertFalse(
            TeamMembership.objects.filter(team=self.team, user=self.bob).exists()
        )

    def test_accept_requires_login(self):
        invite = TeamInvite.objects.create(team=self.team, email="bob@test.com")
        response = self.client.get(f"/teams/invite/{invite.token}/")
        self.assertEqual(response.status_code, 302)
        self.assertIn("/accounts/login/", response.url)


class ActiveTeamResolutionTests(TestCase):
    """get_active_team falls back to Personal when the reference is stale."""

    def setUp(self):
        self.factory_client = Client()
        self.alice = User.objects.create_user("alice", "alice@test.com", "pass1234")
        self.team = Team.objects.create(name="Platform", created_by=self.alice)
        TeamMembership.objects.create(
            team=self.team, user=self.alice, role=TeamMembership.Role.ADMIN
        )

    def _request_with_session(self, user, session_data):
        from django.contrib.sessions.backends.db import SessionStore
        from django.test import RequestFactory

        request = RequestFactory().get("/")
        request.user = user
        request.session = SessionStore()
        for k, v in session_data.items():
            request.session[k] = v
        return request

    def test_returns_team_when_member(self):
        request = self._request_with_session(self.alice, {"active_team_id": self.team.pk})
        self.assertEqual(get_active_team(request), self.team)

    def test_returns_none_when_not_member(self):
        bob = User.objects.create_user("bob", "bob@test.com", "pass1234")
        request = self._request_with_session(bob, {"active_team_id": self.team.pk})
        self.assertIsNone(get_active_team(request))

    def test_returns_none_when_unset(self):
        request = self._request_with_session(self.alice, {})
        self.assertIsNone(get_active_team(request))
