# Generated by Django 6.0.6 on 2026-06-30 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField()),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_logs', to='monitors.monitor')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['monitor', '-checked_at'], name='checklog_monitor_checked')],
            },
        ),
    ]
