# Generated by Django 6.0.6 on 2026-07-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_checklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
