# Generated by Django 6.0.6 on 2026-07-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0003_monitor_is_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='ssl_error',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='monitor',
            name='ssl_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='ssl_expiry_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitor',
            name='ssl_issuer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='monitor',
            name='ssl_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
