# Generated by Django 6.0.6 on 2026-07-02 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0004_monitor_ssl_error_monitor_ssl_expiry_date_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitors', to='teams.team'),
        ),
    ]
