# Generated by Django 6.0.6 on 2026-07-01 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('slack', 'Slack'), ('webhook', 'Webhook'), ('sms', 'SMS')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('slack_access_token', models.CharField(blank=True, default='', max_length=512)),
                ('slack_channel_id', models.CharField(blank=True, default='', max_length=100)),
                ('slack_channel_name', models.CharField(blank=True, default='', max_length=200)),
                ('slack_team_name', models.CharField(blank=True, default='', max_length=200)),
                ('webhook_url', models.URLField(blank=True, default='', max_length=2048)),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=255)),
                ('sms_phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
