# Generated by Django 6.0.6 on 2026-07-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationchannel',
            name='push_relay_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_type',
            field=models.CharField(choices=[('slack', 'Slack'), ('webhook', 'Webhook'), ('sms', 'SMS'), ('push_relay', 'Web Push (Push Relay)')], max_length=20),
        ),
    ]
